== 알고리즘 설계

[arabic]
유사코드 및 단계적 개량

stepwise refinement

작업 설명 → 알고리즘의 초안 → 프로그래밍 언어로 번역

설계후 프로그램이 완전한 명세를 갖추었는지 확인 , 어떤 정보를 입출력,
어떤 계산을 수행할지 파악하기

== 3N + 1

foolproof 프로그램을 쓰도록 노력하기

== 코딩, 디버깅, 테스팅

tip : 오류를 이해하고 오류를 수정해라

tip : 버그 찾기는 자신의 선입견 보다 컴퓨터가 하는 방식을 따르기

tip : 당신의 프로그램의 모든것이 옳다고 확신하면서 여전히 프로그램이
작동하지 않는다면 확신하는 것중 하나는 잘못됐다는것.

for문에서 off-by-one-error 해결은 최종값 여부를 생각하면 된다.

== switch 문

다방향 if문이 있을경우, switch문이 효율적일 수있다. 하나의 표현식을
평가하여 correct case로 바로 이동하기 때문

switch의 표현식 자료형이 enum일 수 있음.

switch문도 definite assignment 오류 발생 할수있다. 간단한 해결책으로는
최종 case를 default로 교체하는 것이다.

== 예외 및 Try..catch

제어 흐름을 정성 궤도에서 이탈시키는 예외적인 사례를 처리하는 것이다.

NumberFormaException은 잘못된 문자열을 숫자로 변환할때 발생하는 에러이고

IllegalArgumentaException은 잘못된 값이 매개변수로 서브루틴에 전달될 때
발생할 수 있다.

다음과 같은 형태를 가진다.

[source,java]
----
try {
statements-1
}
catch (exception-class-name variable-name) {
statements-2
}
----

예외를 포착하고 프로그램을 계속 진행하는 것이 언제나 좋은 생각은 아니다.
왜냐하면 나중에 훨씬 더 큰 혼란으로 이어질 수 있기 때문이다.

== 배열

배열은 각각의 개별 항목을 위치 번호로 참조할 수 있도록 항목을 번호순으로
배열하는 데이터 구조다.

int 배열은 자동으로 0, Char은 유니코드 0, String은 Null로

배열의 개별 항목 자료형을 기본 자료형이라고 한다.

배열의 큰 장점중 하나는 random access가 가능하다는 것이다.
